CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Categories" (
    "CategoryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Icon" text,
    "ColorHex" text,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("CategoryId")
);

CREATE TABLE "Users" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text,
    "PasswordHash" text NOT NULL,
    "Role" character varying(20) NOT NULL DEFAULT 'User',
    "AvatarUrl" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastLoginAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
);

CREATE TABLE "Places" (
    "PlaceId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text,
    "Address" text NOT NULL,
    "Latitude" numeric(10,7) NOT NULL,
    "Longitude" numeric(10,7) NOT NULL,
    "Phone" text,
    "Website" text,
    "OpenTime" time without time zone,
    "CloseTime" time without time zone,
    "PriceMin" numeric,
    "PriceMax" numeric,
    "AverageRating" double precision NOT NULL,
    "TotalReviews" integer NOT NULL,
    "TotalVisits" integer NOT NULL,
    "IsApproved" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "CategoryId" integer,
    "OwnerId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Places" PRIMARY KEY ("PlaceId"),
    CONSTRAINT "FK_Places_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("CategoryId"),
    CONSTRAINT "FK_Places_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("UserId") ON DELETE RESTRICT
);

CREATE TABLE "UserTracking" (
    "TrackId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Latitude" numeric(10,7) NOT NULL,
    "Longitude" numeric(10,7) NOT NULL,
    "Accuracy" double precision,
    "RecordedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_UserTracking" PRIMARY KEY ("TrackId"),
    CONSTRAINT "FK_UserTracking_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "PlaceImages" (
    "ImageId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlaceId" integer NOT NULL,
    "ImageUrl" text NOT NULL,
    "IsMain" boolean NOT NULL,
    "SortOrder" integer NOT NULL,
    CONSTRAINT "PK_PlaceImages" PRIMARY KEY ("ImageId"),
    CONSTRAINT "FK_PlaceImages_Places_PlaceId" FOREIGN KEY ("PlaceId") REFERENCES "Places" ("PlaceId") ON DELETE CASCADE
);

CREATE TABLE "Reviews" (
    "ReviewId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "PlaceId" integer NOT NULL,
    "Rating" tinyint NOT NULL,
    "Comment" text,
    "OwnerReply" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("ReviewId"),
    CONSTRAINT "FK_Reviews_Places_PlaceId" FOREIGN KEY ("PlaceId") REFERENCES "Places" ("PlaceId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Reviews_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE RESTRICT
);

CREATE TABLE "VisitHistory" (
    "VisitId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "PlaceId" integer NOT NULL,
    "CheckInTime" timestamp with time zone NOT NULL,
    "CheckOutTime" timestamp with time zone,
    "DurationMins" integer,
    "AutoDetected" boolean NOT NULL,
    "Notes" text,
    CONSTRAINT "PK_VisitHistory" PRIMARY KEY ("VisitId"),
    CONSTRAINT "FK_VisitHistory_Places_PlaceId" FOREIGN KEY ("PlaceId") REFERENCES "Places" ("PlaceId") ON DELETE RESTRICT,
    CONSTRAINT "FK_VisitHistory_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE RESTRICT
);

INSERT INTO "Categories" ("CategoryId", "ColorHex", "Icon", "Name")
VALUES (1, '#FF5733', '🍜', 'Nhà hàng');
INSERT INTO "Categories" ("CategoryId", "ColorHex", "Icon", "Name")
VALUES (2, '#8B4513', '☕', 'Cà phê');
INSERT INTO "Categories" ("CategoryId", "ColorHex", "Icon", "Name")
VALUES (3, '#2196F3', '🏨', 'Khách sạn');
INSERT INTO "Categories" ("CategoryId", "ColorHex", "Icon", "Name")
VALUES (4, '#4CAF50', '🏛️', 'Tham quan');
INSERT INTO "Categories" ("CategoryId", "ColorHex", "Icon", "Name")
VALUES (5, '#9C27B0', '🎡', 'Vui chơi');
INSERT INTO "Categories" ("CategoryId", "ColorHex", "Icon", "Name")
VALUES (6, '#FF9800', '🛍️', 'Mua sắm');

CREATE INDEX "IX_PlaceImages_PlaceId" ON "PlaceImages" ("PlaceId");

CREATE INDEX "IX_Places_CategoryId" ON "Places" ("CategoryId");

CREATE INDEX "IX_Places_Latitude_Longitude" ON "Places" ("Latitude", "Longitude");

CREATE INDEX "IX_Places_OwnerId" ON "Places" ("OwnerId");

CREATE INDEX "IX_Reviews_PlaceId" ON "Reviews" ("PlaceId");

CREATE UNIQUE INDEX "IX_Reviews_UserId_PlaceId" ON "Reviews" ("UserId", "PlaceId");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE INDEX "IX_UserTracking_UserId_RecordedAt" ON "UserTracking" ("UserId", "RecordedAt");

CREATE INDEX "IX_VisitHistory_PlaceId" ON "VisitHistory" ("PlaceId");

CREATE INDEX "IX_VisitHistory_UserId" ON "VisitHistory" ("UserId");

SELECT setval(
    pg_get_serial_sequence('"Categories"', 'CategoryId'),
    GREATEST(
        (SELECT MAX("CategoryId") FROM "Categories") + 1,
        nextval(pg_get_serial_sequence('"Categories"', 'CategoryId'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260314172516_InitialCreate', '10.0.4');

COMMIT;

START TRANSACTION;
DROP INDEX "IX_Places_Latitude_Longitude";

DELETE FROM "Categories"
WHERE "CategoryId" = 6;

ALTER TABLE "UserTracking" ALTER COLUMN "Longitude" TYPE double precision;

ALTER TABLE "UserTracking" ALTER COLUMN "Latitude" TYPE double precision;

ALTER TABLE "Reviews" ALTER COLUMN "Rating" TYPE smallint;

ALTER TABLE "Reviews" ADD "HiddenNote" text;

ALTER TABLE "Reviews" ADD "IsHidden" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Reviews" ADD "PriceRating" smallint;

ALTER TABLE "Reviews" ADD "SpaceRating" smallint;

ALTER TABLE "Reviews" ADD "TasteRating" smallint;

ALTER TABLE "Places" ALTER COLUMN "Status" DROP DEFAULT;

ALTER TABLE "Places" ALTER COLUMN "Specialty" TYPE character varying(500);

ALTER TABLE "Places" ALTER COLUMN "Radius" DROP DEFAULT;

ALTER TABLE "Places" ALTER COLUMN "OpenStatus" DROP DEFAULT;

ALTER TABLE "Places" ALTER COLUMN "Longitude" TYPE double precision;

ALTER TABLE "Places" ALTER COLUMN "Latitude" TYPE double precision;

ALTER TABLE "Places" ALTER COLUMN "District" TYPE character varying(50);

CREATE TABLE "Complaints" (
    "ComplaintId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "PlaceId" integer,
    "ReviewId" integer,
    "Type" text NOT NULL,
    "Title" text NOT NULL,
    "Content" text NOT NULL,
    "Status" text NOT NULL,
    "AdminReply" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ResolvedAt" timestamp with time zone,
    CONSTRAINT "PK_Complaints" PRIMARY KEY ("ComplaintId"),
    CONSTRAINT "FK_Complaints_Places_PlaceId" FOREIGN KEY ("PlaceId") REFERENCES "Places" ("PlaceId"),
    CONSTRAINT "FK_Complaints_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE RESTRICT
);

CREATE TABLE "Messages" (
    "MessageId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlaceId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "Content" text NOT NULL,
    "IsFromOwner" boolean NOT NULL,
    "ParentId" integer,
    "IsPublic" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("MessageId"),
    CONSTRAINT "FK_Messages_Messages_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Messages" ("MessageId"),
    CONSTRAINT "FK_Messages_Places_PlaceId" FOREIGN KEY ("PlaceId") REFERENCES "Places" ("PlaceId") ON DELETE CASCADE,
    CONSTRAINT "FK_Messages_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Promotions" (
    "PromoId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlaceId" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "Discount" integer,
    "VoucherCode" text,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Promotions" PRIMARY KEY ("PromoId"),
    CONSTRAINT "FK_Promotions_Places_PlaceId" FOREIGN KEY ("PlaceId") REFERENCES "Places" ("PlaceId") ON DELETE CASCADE
);

CREATE TABLE "RefreshTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Token" text NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsRevoked" boolean NOT NULL,
    "DeviceInfo" text,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Staff" (
    "StaffId" integer GENERATED BY DEFAULT AS IDENTITY,
    "PlaceId" integer NOT NULL,
    "UserId" integer,
    "FullName" text NOT NULL,
    "Phone" text,
    "Role" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "JoinedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Staff" PRIMARY KEY ("StaffId"),
    CONSTRAINT "FK_Staff_Places_PlaceId" FOREIGN KEY ("PlaceId") REFERENCES "Places" ("PlaceId") ON DELETE CASCADE
);

UPDATE "Categories" SET "ColorHex" = '#ef4444', "Icon" = '🍽️'
WHERE "CategoryId" = 1;

UPDATE "Categories" SET "ColorHex" = '#f97316', "Icon" = '🥢', "Name" = 'Quán ăn vặt'
WHERE "CategoryId" = 2;

UPDATE "Categories" SET "ColorHex" = '#8b5cf6', "Icon" = '☕', "Name" = 'Cà phê'
WHERE "CategoryId" = 3;

UPDATE "Categories" SET "ColorHex" = '#ec4899', "Icon" = '🧋', "Name" = 'Trà sữa & Đồ uống'
WHERE "CategoryId" = 4;

UPDATE "Categories" SET "ColorHex" = '#eab308', "Icon" = '🍰', "Name" = 'Bánh & Tráng miệng'
WHERE "CategoryId" = 5;

CREATE INDEX "IX_Complaints_PlaceId" ON "Complaints" ("PlaceId");

CREATE INDEX "IX_Complaints_UserId" ON "Complaints" ("UserId");

CREATE INDEX "IX_Messages_ParentId" ON "Messages" ("ParentId");

CREATE INDEX "IX_Messages_PlaceId" ON "Messages" ("PlaceId");

CREATE INDEX "IX_Messages_UserId" ON "Messages" ("UserId");

CREATE INDEX "IX_Promotions_PlaceId" ON "Promotions" ("PlaceId");

CREATE UNIQUE INDEX "IX_RefreshTokens_Token" ON "RefreshTokens" ("Token");

CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");

CREATE INDEX "IX_Staff_PlaceId" ON "Staff" ("PlaceId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260408091840_AddMissingColumnsToPlace', '10.0.4');

COMMIT;

